site_name: Cloud Foundry BOSH
pages:
- About:
  - Welcome: index.md
  - Project Goals: goals-of-bosh.md
  - Community: ecosystem/community.md
- Installation:
  - Installing the CLI: existing-docs/cli-v2-install.md
  - Quick Start: existing-docs/quick-start.md
  - Amazon Web Services: existing-docs/init-aws.md
  - Google Cloud Platform: existing-docs/init-google.md
  - Microsoft Azure: existing-docs/init-azure.md
  - OpenStack: existing-docs/init-openstack.md
  - SoftLayer: existing-docs/init-softlayer.md
  - VirtualBox: existing-docs/bosh-lite.md
  - VMware vCloud: existing-docs/init-vcloud.md
  - VMware vSphere: existing-docs/init-vsphere.md
- Guides:
  - Deploying Software:
    - Core Concepts:
      - Updating Cloud Config: existing-docs/update-cloud-config.md
      - Building a Manifest: existing-docs/deployment-basics.md
      - Uploading Stemcells: existing-docs/uploading-stemcells.md
      - Uploading Releases: existing-docs/uploading-releases.md
      - Deploying: existing-docs/deploying.md
    - Using Persistent Disks:
      - Manually Attaching Disks: existing-docs/persistent-disks.md
      - Orphan Disks: existing-docs/persistent-disks.md
      - Taking Snapshots: existing-docs/snapshots.md
      - Using XFS: existing-docs/persistent-disk-fs.md
    - Using Links:
      - Using Implicit Links: existing-docs/links.md
      - Sharing Links: existing-docs/links.md
      - Manually Configuring Links: existing-docs/links-manual.md
    - Running Errands: existing-docs/errands.md
    - VM Anti-Affinity: existing-docs/vm-anti-affinity.md
    - Troubleshooting:
      - Monitoring: existing-docs/monitoring.md
      - Process Monitoring with Monit: existing-docs/vm-monit.md
      - IaaS Reconciliation: existing-docs/cck.md
    - Migrating:
      - To Availability Zones: existing-docs/migrated-from.md
      - From the Ruby CLI: existing-docs/cli-v2-diff.md
  - Packaging Software:
    - Core Concepts:
      - Creating a Release: existing-docs/create-release.md
    - Using Links:
      - Sharing Properties: existing-docs/links-properties.md
    - Configuring the Blobstore:
      - Release Blobstore: existing-docs/release-blobstore.md
      - Using S3 & IAM Policies: existing-docs/s3-release-blobstore.md
    - Working with Blobs: existing-docs/release-blobs.md
    - Testing:
      - Unit Testing Job Templates: existing-docs/job-templates.md
    - Scheduled Processes: existing-docs/scheduled-procs.md
    - Creating Compiled Releases: existing-docs/compiled-releases.md
    - Using Errands: existing-docs/errands.md
    - Configuring Processes:
      - Recommended Property Types: existing-docs/props-common.md
    - Packaging and Compiling:
      - Creating Packages: existing-docs/packages.md
      - Reusing Packages: existing-docs/package-vendoring.md
    - Windows Compatibility:
      - Overview: existing-docs/windows.md
      - Sample Release: existing-docs/windows-sample-release.md
  - Operating Director:
    - Monitoring:
      - Auditing Events: existing-docs/events.md
      - Reviewing Tasks: existing-docs/director-tasks.md
      - Logging API Access: existing-docs/director-access-events.md
    - Securing:
      - Using Basic Users: existing-docs/director-users.md
      - Integrating with UAA:
        - Configuring Director: existing-docs/director-users-uaa.md
        - Using Teams: existing-docs/director-users-uaa-perms.md
      - Configuring SSL Certificates: existing-docs/director-certs.md
    - Configuring the Database:
      - Builtin PostgreSQL: existing-docs/director-configure-db.md
      - External MySQL: existing-docs/director-configure-db.md
    - Configuring the Blobstore:
      - Builtin DAV Server: existing-docs/director-configure-blobstore.md
      - Amazon S3: existing-docs/director-configure-blobstore.md
      - Google Cloud Storage: existing-docs/director-configure-blobstore.md
    - Managing Releases: existing-docs/managing-releases.md
    - Managing Stemcells: existing-docs/managing-stemcells.md
    - Auto-healing Capabilities: existing-docs/resurrector.md
    - Using Health Monitor: existing-docs/hm-config.md
    - Common Addons: existing-docs/addons-common.md
    - Integrating with CredHub:
      - Variable Types: existing-docs/variable-types.md
    - Optional Features:
      - Explicit ARP Flushing: existing-docs/flush-arp.md
      - Removing Dev Tools from VMs: existing-docs/remove-dev-tools.md
      - Installing Certificates on VMs: existing-docs/trusted-certs.md
    - Troubleshooting: existing-docs/tips.md
  - Using the CLI:
    - Commands: existing-docs/cli-v2.md
    - Global Flags: existing-docs/cli-global-flags.md
    - Environments: existing-docs/cli-envs.md
    - Tunneling: existing-docs/cli-tunnel.md
    - Composing YAML:
      - Interpolating Variables: existing-docs/cli-int.md
      - Creating Ops Files: existing-docs/cli-ops-files.md
  - Advanced Networking:
    - Multi-Cloud Support:
      - Using CPI Config: existing-docs/cpi-config.md
      - Using AWS: existing-docs/guide-multi-cpi-aws.md
    - Using IPv6 on vSphere: existing-docs/guide-ipv6-on-vsphere.md
  - Advanced Bootstrapping:
    - Using a Public IP: existing-docs/init-external-ip.md
    - Enabling SSH Access: existing-docs/jumpbox.md
    - Recovering a State File: bosh-cli/guide/recovering-env-state.md
  - In-depth Topics:
    - Native DNS Support: existing-docs/dns.md
    - Components of BOSH: existing-docs/bosh-components.md
    - Deploying Step by Step: existing-docs/deploying-step-by-step.md
    - Agent Interactions: existing-docs/agent-cpi-interactions.md
    - Virtual Machines:
      - Structure of a VM: existing-docs/vm-struct.md
      - Configuration Locations: existing-docs/vm-config.md
      - Using Logs: existing-docs/job-logs.md
      - Instance Metadata: existing-docs/instance-metadata.md
  - Development:
    - Building a CPI: existing-docs/build-cpi.md
    - Building a Stemcell: existing-docs/build-stemcell.md
    - Repacking Stemcells: existing-docs/repack-stemcell.md
    - Target Personas: existing-docs/personas.md
- Reference:
  - Terminology: existing-docs/terminology.md
  - Release Notes:
    - Ubuntu Trusty Stemcell:
      - 3541.x: bosh-linux-stemcell-builder/release-notes/3541.x.md
  - Deployment Config: existing-docs/manifest-v2.md
  - Director Cloud Config:
    - Usage: existing-docs/cloud-config.md
    - Availability Zones: existing-docs/azs.md
    - Networks: existing-docs/networks.md
  - Director HTTP API: existing-docs/director-api-v1.md
  - Director Runtime Config:
    - Usage: existing-docs/runtime-config.md
  - Generic Configs: existing-docs/configs.md
  - Cloud Provider Interface: existing-docs/cpi-api-v1.md
  - Release Management:
    - Overview: existing-docs/release.md
    - Release URLs: existing-docs/release-urls.md
    - Jobs:
      - Usage: existing-docs/jobs.md
      - Update Lifecycle: existing-docs/job-lifecycle.md
      - Lifecycle Hooks:
        - Drain: existing-docs/drain.md
        - Pre-start: existing-docs/pre-start.md
        - Post-start: existing-docs/post-start.md
        - Post-deploy: existing-docs/post-deploy.md
    - Links:
      - Common Types: existing-docs/links-common-types.md
  - Amazon Web Services:
    - Usage: existing-docs/aws-cpi.md
    - IAM Users: existing-docs/aws-iam-users.md
    - IAM Profiles: existing-docs/aws-iam-instance-profiles.md
    - Using Instance Storage: existing-docs/aws-instance-storage.md
  - Google Cloud Platform:
    - Usage: existing-docs/google-cpi.md
    - Required Permissions: existing-docs/google-required-permissions.md
  - Microsoft Azure:
    - Usage: existing-docs/azure-cpi.md
    - Creating Resources: existing-docs/azure-resources.md
  - OpenStack:
    - Usage: existing-docs/openstack-cpi.md
    - Using Auto-anti-affinity: existing-docs/openstack-auto-anti-affinity.md
    - Using Human-readable VM names: existing-docs/openstack-human-readable-vm-names.md
    - Using Keystone API v2: existing-docs/openstack-keystonev2.md
    - Using Light Stemcells: existing-docs/openstack-light-stemcells.md
    - Using nova-networking: existing-docs/openstack-nova-networking.md
    - Multi-homed VMs: existing-docs/openstack-multiple-networks.md
    - Extended Registry configuration: existing-docs/openstack-registry.md
    - Self-signed Endpoints: existing-docs/openstack-self-signed-endpoints.md
  - RackHD:
    - Usage: existing-docs/rackhd-cpi.md
  - SoftLayer:
    - Usage: existing-docs/softlayer-cpi.md
  - VirtualBox:
    - Usage: existing-docs/virtualbox-cpi.md
  - VMware vCloud:
    - Usage: existing-docs/vcloud-cpi.md
  - VMware vSphere:
    - Usage: existing-docs/vsphere-cpi.md
    - Recovery from an ESXi Host Failure: existing-docs/vsphere-esxi-host-failure.md
    - vSphere High Availability: existing-docs/vsphere-ha.md
    - Migrating Datastores: existing-docs/vsphere-migrate-datastores.md
    - Recovery from a vSphere Network Partitioning Fault: existing-docs/vsphere-network-partition.md
    - Storage DRS and vMotion Support: existing-docs/vsphere-vmotion-support.md
    - Bootstrapping with Resource Pools: existing-docs/init-vsphere-rp.md
  - Warden:
    - Usage: existing-docs/warden-cpi.md
  - Legacy Documentation:
    - What is a Deployment?: existing-docs/deployment.md
    - What is a Stemcell?: existing-docs/stemcell.md
    - Basic Workflow: existing-docs/basic-workflow.md
    - Deployment Manifest v1: existing-docs/deployment-manifest.md
    - CLI v1 Installation: existing-docs/bosh-cli.md
    - CLI v1 Commands: existing-docs/sysadmin-commands.md
    - CLI v1 Backup / Restore: existing-docs/director-backup.md
- Stemcells:
  - Stemcells: stemcells.md
- Releases:
  - Releases: releases.md
theme:
  name: 'material'
  feature:
    tabs: true
  palette:
    primary: blue
    accent: blue
  logo: images/logo.png
markdown_extensions: # based on docs-cfcr
- markdown.extensions.admonition
- markdown.extensions.codehilite
- markdown.extensions.def_list
- markdown.extensions.footnotes
- markdown.extensions.meta
- markdown.extensions.toc(permalink=true)
- pymdownx.arithmatex
- pymdownx.betterem(smart_enable=all)
- pymdownx.caret
- pymdownx.critic
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_svg
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist(custom_checkbox=true)
- pymdownx.tilde
extra:
  social:
    - type: 'github'
      link: 'https://github.com/cloudfoundry/bosh'
    - type: 'slack'
      link: 'https://cloudfoundry.slack.com/messages/C02HPPYQ2/'
