site_name: Cloud Foundry BOSH
repo_name: 'cloudfoundry/docs-bosh'
repo_url: 'https://github.com/cloudfoundry/docs-bosh'
edit_uri: edit/master/
pages:
- About:
  - Welcome: index.md
  - Project Goals: problems.md
  - Community: community.md
- Installation:
  - Installing the CLI: cli-v2-install.md
  - Quick Start: quick-start.md
  - Amazon Web Services: init-aws.md
  - Google Cloud Platform: init-google.md
  - Microsoft Azure: init-azure.md
  - OpenStack: init-openstack.md
  - SoftLayer: init-softlayer.md
  - VirtualBox: bosh-lite.md
  - VMware vCloud: init-vcloud.md
  - VMware vSphere: init-vsphere.md
- Guides:
  - Deploying Software:
    - Core Concepts:
      - Updating Cloud Config: update-cloud-config.md
      - Building a Manifest: deployment-basics.md
      - Uploading Stemcells: uploading-stemcells.md
      - Uploading Releases: uploading-releases.md
      - Deploying: deploying.md
    - Using Persistent Disks:
      - Manually Attaching Disks: persistent-disks.md
      - Orphan Disks: persistent-disks.md
      - Taking Snapshots: snapshots.md
      - Using XFS: persistent-disk-fs.md
    - Using Links:
      - Using Implicit Links: links.md
      - Sharing Links: links.md
      - Manually Configuring Links: links-manual.md
    - Running Errands: errands.md
    - VM Anti-Affinity: vm-anti-affinity.md
    - Troubleshooting:
      - Monitoring: monitoring.md
      - Process Monitoring with Monit: vm-monit.md
      - IaaS Reconciliation: cck.md
    - Migrating:
      - To Availability Zones: migrated-from.md
      - From the Ruby CLI: cli-v2-diff.md
  - Packaging Software:
    - Core Concepts:
      - Creating a Release: create-release.md
    - Using Links:
      - Sharing Properties: links-properties.md
    - Configuring the Blobstore:
      - Release Blobstore: release-blobstore.md
      - Using S3 & IAM Policies: s3-release-blobstore.md
    - Working with Blobs: release-blobs.md
    - Testing:
      - Unit Testing Job Templates: job-templates.md
    - Scheduled Processes: scheduled-procs.md
    - Creating Compiled Releases: compiled-releases.md
    - Using Errands: errands.md
    - Configuring Processes:
      - Recommended Property Types: props-common.md
    - Packaging and Compiling:
      - Creating Packages: packages.md
      - Reusing Packages: package-vendoring.md
    - Windows Compatibility:
      - Overview: windows.md
      - Sample Release: windows-sample-release.md
  - Operating Director:
    - Monitoring:
      - Auditing Events: events.md
      - Reviewing Tasks: director-tasks.md
      - Logging API Access: director-access-events.md
    - Securing:
      - Using Basic Users: director-users.md
      - Integrating with UAA:
        - Configuring Director: director-users-uaa.md
        - Using Teams: director-users-uaa-perms.md
      - Configuring SSL Certificates: director-certs.md
    - Configuring the Database:
      - Builtin PostgreSQL: director-configure-db.md
      - External MySQL: director-configure-db.md
    - Configuring the Blobstore:
      - Builtin DAV Server: director-configure-blobstore.md
      - Amazon S3: director-configure-blobstore.md
      - Google Cloud Storage: director-configure-blobstore.md
    - Managing Releases: managing-releases.md
    - Managing Stemcells: managing-stemcells.md
    - Auto-healing Capabilities: resurrector.md
    - Using Health Monitor: hm-config.md
    - Using Runtime Config:
      - Overview: runtime-config.md
      - Common Addons: addons-common.md
    - Integrating with CredHub:
      - Variable Types: variable-types.md
    - Optional Features:
      - Explicit ARP Flushing: flush-arp.md
      - Removing Dev Tools from VMs: remove-dev-tools.md
      - Installing Certificates on VMs: trusted-certs.md
    - Troubleshooting: tips.md
  - Using the CLI:
    - Commands: cli-v2.md
    - Global Flags: cli-global-flags.md
    - Environments: cli-envs.md
    - Tunneling: cli-tunnel.md
    - Composing YAML:
      - Interpolating Variables: cli-int.md
      - Creating Ops Files: cli-ops-files.md
  - Advanced Networking:
    - Multi-Cloud Support:
      - Using CPI Config: cpi-config.md
      - Using AWS: guide-multi-cpi-aws.md
    - Using IPv6 on vSphere: guide-ipv6-on-vsphere.md
  - Advanced Bootstrapping:
    - Using a Public IP: init-external-ip.md
    - Enabling SSH Access: jumpbox.md
  - In-depth Topics:
    - Native DNS Support: dns.md
    - Components of BOSH: bosh-components.md
    - Deploying Step by Step: deploying-step-by-step.md
    - Agent Interactions: agent-cpi-interactions.md
    - Virtual Machines:
      - Structure of a VM: vm-struct.md
      - Configuration Locations: vm-config.md
      - Using Logs: job-logs.md
      - Instance Metadata: instance-metadata.md
  - Development:
    - Building a CPI: build-cpi.md
    - Building a Stemcell: build-stemcell.md
    - Repacking Stemcells: repack-stemcell.md
    - Target Personas: personas.md
- Reference:
  - Terminology: terminology.md
  - Deployment Config:
    - Schema (UI Test Before): manifest-v2.md
    - Schema (UI Test After): manifest-v2-schema.md
  - Director Cloud Config:
    - Usage: cloud-config.md
    - Availability Zones: azs.md
    - Networks: networks.md
  - Director HTTP API: director-api-v1.md
  - Director Runtime Config:
    - Schema: runtime-config-schema.md
  - Generic Configs: configs.md
  - Cloud Provider Interface: cpi-api-v1.md
  - Release Management:
    - Overview: release.md
    - Release URLs: release-urls.md
    - Jobs:
      - Usage: jobs.md
      - Update Lifecycle: job-lifecycle.md
      - Lifecycle Hooks:
        - Drain: drain.md
        - Pre-start: pre-start.md
        - Post-start: post-start.md
        - Post-deploy: post-deploy.md
    - Links:
      - Common Types: links-common-types.md
  - Legacy Documentation:
    - What is a Deployment?: deployment.md
    - What is a Stemcell?: stemcell.md
    - Basic Workflow: basic-workflow.md
    - Deployment Manifest v1: deployment-manifest.md
    - CLI v1 Installation: bosh-cli.md
    - CLI v1 Commands: sysadmin-commands.md
    - CLI v1 Backup / Restore: director-backup.md

  - "--- Cloud Providers": divider.md
  - Amazon Web Services:
    - Usage: aws-cpi.md
    - IAM Users: aws-iam-users.md
    - IAM Profiles: aws-iam-instance-profiles.md
    - Using Instance Storage: aws-instance-storage.md
    - Troubleshooting: aws-cpi-troubleshooting.md
  - Google Cloud Platform:
    - Usage: google-cpi.md
    - Required Permissions: google-required-permissions.md
  - Microsoft Azure:
    - Usage: azure-cpi.md
    - Creating Resources: azure-resources.md
  - OpenStack:
    - Usage: openstack-cpi.md
    - Using Auto-anti-affinity: openstack-auto-anti-affinity.md
    - Using Human-readable VM names: openstack-human-readable-vm-names.md
    - Using Keystone API v2: openstack-keystonev2.md
    - Using Light Stemcells: openstack-light-stemcells.md
    - Using nova-networking: openstack-nova-networking.md
    - Multi-homed VMs: openstack-multiple-networks.md
    - Extended Registry configuration: openstack-registry.md
    - Self-signed Endpoints: openstack-self-signed-endpoints.md
  - RackHD:
    - Usage: rackhd-cpi.md
  - SoftLayer:
    - Usage: softlayer-cpi.md
  - VirtualBox:
    - Usage: virtualbox-cpi.md
  - VMware vCloud:
    - Usage: vcloud-cpi.md
  - VMware vSphere:
    - Usage: vsphere-cpi.md
    - Recovery from an ESXi Host Failure: vsphere-esxi-host-failure.md
    - vSphere High Availability: vsphere-ha.md
    - Migrating Datastores: vsphere-migrate-datastores.md
    - Recovery from a vSphere Network Partitioning Fault: vsphere-network-partition.md
    - Storage DRS and vMotion Support: vsphere-vmotion-support.md
    - Bootstrapping with Resource Pools: init-vsphere-rp.md
  - Warden:
    - Usage: warden-cpi.md
- Stemcells:
  - Stemcells: stemcells.md
- Releases:
  - Releases: releases.md
# this hack avoids divider.md showing up in navigation and site search
- "--- ": divider.md
theme:
  name: material
  custom_dir: theme
  feature:
    tabs: true
  palette:
    primary: blue
    accent: blue
  logo: images/logo.png
extra_css:
  - 'stylesheets/extra.css'
markdown_extensions: # based on docs-cfcr
- markdown.extensions.admonition
- markdown.extensions.codehilite
- markdown.extensions.def_list
- markdown.extensions.attr_list
- markdown.extensions.footnotes
- markdown.extensions.meta
- markdown.extensions.toc(permalink=true)
- pymdownx.arithmatex
- pymdownx.betterem(smart_enable=all)
- pymdownx.caret
- pymdownx.critic
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_svg
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist(custom_checkbox=true)
- pymdownx.tilde
extra:
  social:
    - type: 'github'
      link: 'https://github.com/cloudfoundry/bosh'
    - type: 'slack'
      link: 'https://cloudfoundry.slack.com/messages/C02HPPYQ2/'
